function initializeCues()
  cue = {}
  cue["countIn1"] = newSource("/resources/sfx/game/countIn1.ogg")
  cue["countIn2"] = newSource("/resources/sfx/game/countIn2.ogg")
  cue["countIn3"] = newSource("/resources/sfx/game/countIn3.ogg")
  cue["countIn4"] = newSource("/resources/sfx/game/countIn4.ogg")
  cue["cowbell"] = newSource("/resources/sfx/game/cowbell.ogg")
  cue["silence"] = newSource("/resources/sfx/silence.ogg")
  cue["karatekaPotThrow"] = newSource("/resources/sfx/karate man (GBA)/potThrow.ogg")
  cue["karatekaPotHit"] = newSource("/resources/sfx/karate man (GBA)/potHit.ogg")
  cue["karatekaRockHit"] = newSource("/resources/sfx/karate man (GBA)/rockHit.ogg")
  cue["karatekaMi"] = newSource("/resources/sfx/karate man (GBA)/mi.ogg")
  cue["karatekaTsu"] = newSource("/resources/sfx/karate man (GBA)/tsu.ogg")
  cue["tweezersRootAppear"] = newSource("/resources/sfx/rhythm tweezers (GBA)/hairAppear.ogg")
  cue["tweezersRootPluck"] = newSource("/resources/sfx/rhythm tweezers (GBA)/hairPluck.ogg")
  cue["tweezersRootAppearLong"] = newSource("/resources/sfx/rhythm tweezers (GBA)/hairAppearLong.ogg")
  cue["tweezersRootPluckLong1"] = newSource("/resources/sfx/rhythm tweezers (GBA)/hairPluckLong1.ogg")
  cue["tweezersRootPluckLong2"] = newSource("/resources/sfx/rhythm tweezers (GBA)/hairPluckLong2.ogg")
  cue["BlueBirdsPeck"] = newSource("/resources/sfx/Blue birds/peck.ogg")
  cue["BlueBirdsYour"] = newSource("/resources/sfx/Blue birds/your.ogg")
  cue["BlueBirdsBeak"] = newSource("/resources/sfx/Blue birds/beak.ogg")
  cue["BlueBirdsPeckPlayer"] = newSource("/resources/sfx/Blue birds/peckPlayer.ogg")
  cue["BlueBirdsStretch"] = newSource("/resources/sfx/Blue birds/stretch.ogg")
  cue["BlueBirdsOut"] = newSource("/resources/sfx/Blue birds/out.ogg")
  cue["BlueBirdsYour2"] = newSource("/resources/sfx/Blue birds/your2.ogg")
  cue["BlueBirdsNeck"] = newSource("/resources/sfx/Blue birds/neck.ogg")
  cue["BlueBirdsStretchPlayer1"] = newSource("/resources/sfx/Blue birds/stretchPlayer1.ogg")
  cue["BlueBirdsStretchPlayer2"] = newSource("/resources/sfx/Blue birds/stretchPlayer2.ogg")
  cue["ForkLifterFlick"] = newSource("/resources/sfx/Fork Lifter/flick.ogg")
  cue["ForkLifterZoom"] = newSource("/resources/sfx/Fork Lifter/zoom.ogg")
  cue["ForkLifterStab"] = newSource("/resources/sfx/Fork Lifter/stab.ogg")
  cue["ForkLifterEat"] = newSource("/resources/sfx/Fork Lifter/eat.ogg")
  cue["ClappyTrioPrep"] = newSource("/resources/sfx/Clappy Trio (Wii)/prepare.ogg")
  cue["ClappyTrioClap"] = newSource("/resources/sfx/Clappy Trio (Wii)/clap.ogg")
  cue["LockStepOn"] = newSource("/resources/sfx/Lock step/stepOn.ogg")
  cue["LockStepOff"] = newSource("/resources/sfx/Lock step/stepOff.ogg")
  cue["LockStepHai"] = newSource("/resources/sfx/Lock step/hai.ogg")
  cue["LockStepHa"] = newSource("/resources/sfx/Lock step/ha.ogg")
  cue["LockStepHaOff"] = newSource("/resources/sfx/Lock step/haOff.ogg")
  cue["LockStepHaiOff"] = newSource("/resources/sfx/Lock step/haiOff.ogg")
  cue["LockStepOuf"] = newSource("/resources/sfx/Lock step/ouf.ogg")
  cue["LockStepHm"] = newSource("/resources/sfx/Lock step/hm.ogg")
  cue["ScrewBotsCrane1"] = newSource("/resources/sfx/screw bots/crane1.ogg")
  cue["ScrewBotsCrane2"] = newSource("/resources/sfx/screw bots/crane2.ogg")
  cue["ScrewBotsCraneWhite"] = newSource("/resources/sfx/screw bots/craneWhite.ogg")
  cue["ScrewBotsBlackDrop"] = newSource("/resources/sfx/screw bots/blackDrop.ogg")
  cue["ScrewBotsBlackScrew"] = newSource("/resources/sfx/screw bots/blackScrew.ogg")
  cue["ScrewBotsWhiteDrop"] = newSource("/resources/sfx/screw bots/whiteDrop.ogg")
  cue["ScrewBotsWhiteScrew"] = newSource("/resources/sfx/screw bots/whiteScrew.ogg")
  cue["ScrewBotsComplete"] = newSource("/resources/sfx/screw bots/complete.ogg")
end









